version: "2"

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    depends_on: 
      - db
    ports:
      - "9000:9000"
    networks:
      - localnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar?&characterEncoding=UTF-8
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:10-alpine
    container_name: postgres
    networks:
      - localnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  localnet:
    name: localnet
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: